### ISSUE TITLE
Disallow spaces in front of theme Titles?

### ISSUE THREAD

**Issue by blopker** [Colorsublime/Colorsublime-Themes#130]
I noticed some themes take advantage of Title sorting to be shown first:
```json
{
    "Title": " 1337",
    "FileName": "1337.tmTheme",
    "Author": "Mark Michos",
    "Description": "A color scheme for dark Sublime Text themes."
}
{
    "Title": " Dark Room (Normal)",
    "FileName": "DarkRoomNormal.tmTheme",
    "Author": "Neil Cresswell",
    "Description": "Easy on eyes dark theme with accented comments and GitGutter support. See https://github.com/NeilCresswell/themes for other IDEs."
}
```
This is a little unfair to the other themes which don't do this. Maybe this should be checked for in a test and rejected?

**Comment by GianlucaGuarini** [comment]
Could you extend our tests making a pull request? Otherwise I will do it ASAP

**Comment by blopker** [comment]
And, pull request. https://github.com/Colorsublime/Colorsublime-Themes/pull/131
