### ISSUE TITLE
Python syntax highlighter does not properly color some keywords ...

### ISSUE THREAD

**Issue by qbx2** [Colorsublime/Colorsublime-Themes#148]
Python syntax highlighter does not properly color some keywords ...
* def keyword
* function name (when define the function)
* function parameters (when define the function)
* class keyword
* base class names (inheritance)
* Exception keyword
* format placeholders in a format string
* function parameters, kwargs (when call the function)

**Comment by GianlucaGuarini** [comment]
You should submit the issue to the ace editor project. Probably this issue has been already discussed here https://github.com/ajaxorg/ace/issues/2251
Definitely not a color sublime bug but thanks anyway
