### ISSUE TITLE
Request: Base 16, Tomorrow, Dracula

### ISSUE THREAD

**Issue by kevinSuttle** [Colorsublime/Colorsublime-Themes#152]
https://github.com/chriskempson/base16-textmate
https://github.com/chriskempson/tomorrow-theme/tree/master/textmate2
https://github.com/zenorocha/dracula-theme

**Comment by GianlucaGuarini** [comment]
Pull request?

**Comment by kevinSuttle** [comment]
Yeah, was just being lazy/time-constrained. :) I'll put one together.

**Comment by GianlucaGuarini** [comment]
closed due to inactivity
