### ISSUE TITLE
XML "well-formed" parse error

### ISSUE THREAD

**Issue by Xunnamius** [Colorsublime/Colorsublime-Themes#172]
I'm not entirely sure how many Colorsublime themes this applies to, or if it applies to all of them or only the one I'm currently using. I'm using the theme "Acai". It is amazing; however, the comment under the DOCTYPE does not constitute well-formed XML. Hence, it causes SublimeLinter to choke, which leads to several annoyances.

The fix for Acai is as easy as deleting the offending comment:
```
<!--
-------------------------------------------------------
* Acai *

A Sublime Text theme by Travis Lehman (@tehtrav)
A dark theme designed to be easy on the eyes.
-------------------------------------------------------
-->
```

XML validator says "---" is not valid and should not appear where it does.

**Comment by blopker** [comment]
Thank you for the heads up. Which XML validator are you using?

**Comment by GianlucaGuarini** [comment]
I don't get where is the issue..sublime text does not complain about this, colorsublime.com neither.. @Xunnamius have you any issue in sublime? (except browsing the themes code using sublimelinter)

**Comment by blopker** [comment]
Either way, the branch I made is ready to merge. @GianlucaGuarini, you can merge it if you'd like. Otherwise just nuke it ;)

**Comment by GianlucaGuarini** [comment]
fixed thanks

**Comment by Xunnamius** [comment]
@GianlucaGuarini Yes, Sublime doesn't seem to care. It's **SublimeLinter**, which parses theme files in order to determine if it needs to add its own gutter styles, that chokes.

@GianlucaGuarini @blopker Thanks for the fast reply and fix :)
