### ISSUE TITLE
Anarchist Theme Mods

### ISSUE THREAD

**Issue by brianjking** [Colorsublime/Colorsublime-Themes#178]
Hello,

Is there a way when using the Anarchist Theme to edit the tab size (the physical size of each tab when you have multiple files open in the same project).

Secondly, what about sidebar support for Anarchist?

https://github.com/Colorsublime/Colorsublime-Themes/blob/master/themes/Anarchist.tmTheme

Thanks!

**Comment by ritashugisha** [comment]
Anarchist is built for use with Sublime Text's [Spacegray](https://packagecontrol.io/packages/Theme%20-%20Spacegray) UI.

.tmtheme's don't affect any UI feature (so far as I know)... you may want to checkout some of [Spacegray's settings](https://github.com/kkga/spacegray#settings) which do allow variable tab size.

**Comment by GianlucaGuarini** [comment]
closed due to inactivity
