### ISSUE TITLE
Any chance of open sourcing the colorsublime website?

### ISSUE THREAD

**Issue by nickcoutsos** [Colorsublime/Colorsublime-Themes#182]
I've noticed in another issue that you aren't looking to make feature changes to the colorsublime website which is understandable, but is anything preventing you from releasing the source so that users can provide pull requests?

The website is a great resource, but I really wish I could sort themes by date added so that I don't need to browse the entire collection (or git commits) to see what's new. I'd be willing to put the time into making that possible if you want to allow contributions :)

**Comment by blopker** [comment]
I'm still taking improvements to the plugin. You could submit a PR to show themes in the reverse order they show in the `themes.json` file. We should instruct new themes be put at the bottom of that file.
