### ISSUE TITLE
Add proper XML validation, see issue #209

### ISSUE THREAD

**Issue by shakeelmohamed** [Colorsublime/Colorsublime-Themes#210]
I made a fix in #209 to address a malformed theme file, which should've been caught by the tests.

I'm happy to do this work, just wanted to post this for visibility

**Comment by blopker** [comment]
Better tests are definitely something we could use help with. Let me know if you have any questions!

**Comment by shakeelmohamed** [comment]
The test don't really address this case at all, I made a [dummy theme that's super messed](https://github.com/Colorsublime/Colorsublime-Themes/blob/ec0130f662f15013302a3c0f52c80a19fe5009a2/themes/breakme.tmTheme) up and the tests still pass for it.

Looking deeper!

**Comment by GianlucaGuarini** [comment]
This test should be easy and we could handle it parsing the themes with https://www.npmjs.com/package/xmldom I don't know if I will have time to work on it in the next few weeks ( I'm too busy with riotjs ). If any of you guys would like to try I will be more than happy merging your pull request

**Comment by shakeelmohamed** [comment]
@GianlucaGuarini ugh, I really don't wan to write XML parsing code, isn't this a solved problem by now? :tired_face:

We could leverage the `w3cjs` module if we modify the `content-type` header, but that will require a ton of HTTP requests and make the test super slow
