### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by chrisdias** [Colorsublime/Colorsublime-Themes#216]
Hi!

On the http://colorsublime.com/ site you state that all the themes are under the MIT license, which is great!

"This project is build by developers for developers and all the available themes are under the MIT license"

The package.json also refers to the MIT license on line 19.

``` json
  "license": "MIT",
```

The LICENSE file that is checked in is not the MIT license however.  Could you please update this file to be the MIT license?

Thanks,
Chris

**Comment by blopker** [comment]
@GianlucaGuarini, do you approve?

**Comment by GianlucaGuarini** [comment]
:+1: @blopker  thanks
