### ISSUE TITLE
theme suggestion

### ISSUE THREAD

**Issue by jorduino** [Colorsublime/Colorsublime-Themes#287]
I don't know where else to put this, but could you add a theme that uses ubuntu's color palette?

**Comment by robengrobban** [comment]
Hi! Greate idé i will start looking in to it and then submit it to the site!

**Comment by jorduino** [comment]
Hey sorry. I'm not on github a lot, and I didn't see the email until now, but I got the file you linked on my page and I love the theme you chose. Thank you so much!
