### ISSUE TITLE
A few themes are corrupted

### ISSUE THREAD

**Issue by vadi2** [Colorsublime/Colorsublime-Themes#342]
```
NeonGlow.tmTheme:line 564: Name is empty. Cannot parse theme!"
blockninja.tmTheme:line 1: Start element not found!"
RamdaJS.tmTheme:line 292: Name is empty. Cannot parse theme!"
```

**Comment by GianlucaGuarini** [comment]
where do you get this error? In sublime or on the site?

**Comment by vadi2** [comment]
This is using another editor that can parse tmTheme files - https://github.com/edbee/edbee-lib. If I submit a PR to fix these trivial issues, would it be accepted?
