### ISSUE TITLE
http://colorsublime.com/ domain does not work

### ISSUE THREAD

**Issue by imagentleman** [Colorsublime/Colorsublime-Themes#364]
It's returning a forbidden (403) error page.

Noticed that in the twitter announcement (for the new version) the github.io alternate URL was used (https://twitter.com/ColorSublime/status/892333987636686848).

Did you give up on using the .com domain?

**Comment by GianlucaGuarini** [comment]
yep the .com domain was killed in favor of a full open source alternative with no costs or concerns for us regarding maintaining a .com domain
