### ISSUE TITLE
The sexist color theme

### ISSUE THREAD

**Issue by Mopolo** [Colorsublime/Colorsublime-Themes#88]
Hi,

I love your site and use the Aurora theme that I really love.

But I noticed this theme: http://colorsublime.com/theme/Girlfriend

And the description is "Your girlfriend will finally love looking at your code". IT is not just a male thing, there are also women in this industry. And having these kind of phrases will only keep them out of IT.

This theme is sexist and misogynist. It should be removed.

And in case you wonder, I'm a guy, and I find this theme offensive to women.

**Comment by gsinnott** [comment]
This was my favourite theme and now I can't find it. I don't get it - is the use of pastel colours demeaning? Has any women actually objected to the name of the theme? Is this meant to be some kind of weird gallantry you're getting your knickers in twist over? 

Can't find either "Your girlfriend will finally love looking at your code" or "Pastel" - if anyone can point me in the right direction, much appreciated.

**Comment by Mopolo** [comment]
Hi @gsinnott. For some reason the theme was updated to these new colours: http://colorsublime.com/theme/Pastel

The one you are looking for is this one: https://github.com/Colorsublime/Colorsublime-Themes/blob/a00e1769b492e589fd481ff76fdaa805bb181d21/themes/Pastel.tmTheme

If you want an explanation, then all you have to do is read the comments on this issue (the link sent by @geeksam is a good explanation).

**Comment by gsinnott** [comment]
Right, I did. But I still take issue - because to me it seems really quite nasty to publicly shame the creator for having made "The sexist color theme" and call them a misogynist, simply for combining a particularly nice set of colours in a text editing program.

**Comment by Mopolo** [comment]
I don't know what to say so I'll just quote myself:

> And I agree, pinkish theme is not sexist, but the color associated with the description and the name are.

**Comment by gsinnott** [comment]
So when challenged your only recourse is to quote someone half-agreeing with you?

**Comment by Mopolo** [comment]
I said myself so not someone else. This seems a bit overreacting.

I have nothing to add to what has already been said. No need to continue.

**Comment by gsinnott** [comment]
Just think a bit more before throwing about such loaded terms - I think it's far more demeaning for you to take it upon yourself to be the righteous protector of all women on their behalf.

**Comment by blopker** [comment]
> No need to continue.

Agreed.
